shallow_clone: true
platform:
  - x86
services:
  - mongodb
before_build:
  - SET PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - git clone --depth=1 https://github.com/estebanlm/pharo-travis-ci.git
build_script:
  - bash -c "baseline=%BASELINE% packages_dir=%PACKAGES_DIR% pharo_version=%PHARO_VERSION% pharo-travis-ci\run-tests.sh"
on_failure:
  - dir
  - cat PharoDebug.log
environment:
  BASELINE: "VoyageMongo"
  PACKAGES_DIR: "mc"
  PHARO_VERSION: "60"