shallow_clone: true
platform:
  - x86
services:
  - mongodb
before_build:
  - SET PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - git clone --depth=1 https://github.com/estebanlm/pharo-travis-ci.git
build_script:
  - sh pharo-travis-ci\run-tests.sh
after_build:
  - dir
  - cat PharoDebug.log
environment:
  global: 
    baseline: VoyageMongo
    packages_dir: mc
    pharo_version: 50