shallow_clone: true
platform:
  - x86
services:
  - mongodb
before_build:
  - SET PATH=C:\MinGW\msys\1.0\bin;%PATH%
  - git clone --depth=1 https://github.com/estebanlm/pharo-travis-ci.git
build_script:
  - bash pharo-travis-ci\run-tests.sh  
on_failure:
  - dir
  - cat PharoDebug.log
environment:
  global: 
    - baseline=VoyageMongo
    - packages_dir=mc
	- pharo_version=50